Feature/7 adding rg template to folder.
paweltajs/azure-data-lake-infra pull request #10
Opened 2021-09-02 15:39 UTC by curumoLuin

Added LinkedTemplate. Seems to be working but not sure if correctly passing parameters. Review please.

2021-09-03 07:33 UTC, paweltajs requested changes

2021-09-03 07:33 UTC, paweltajs commented on arm-templates/subscription.json
> +        "templateUrlRgMusicLake": "https://raw.githubusercontent.com/paweltajs/azure-data-lake-infra/feature/7-adding-rg-template-to-folder/arm-templates/resources/rg_music_lake.json"
We should pass path to root repository folder as parameter. Later on we should use this basePath to concat it with path to particular file.

2021-09-03 07:33 UTC, paweltajs commented on arm-templates/subscription.json
> +        "rgNameMusicLake": "[concat('rg-music-lake-', parameters('subPrefix')) ]",
Duplicate variable, they represent the same value. Lets make it **rg_music_lake** variable.

2021-09-03 07:33 UTC, paweltajs commented on arm-templates/subscription.json
> +                    "location": {
Make it oneliner if there is only one child.

2021-09-03 07:33 UTC, paweltajs commented on arm-templates/subscription.json
> +                    "rgName": {
Make it oneliner if there is only one child. Use rg_music_lake as a name,

2021-09-03 07:33 UTC, paweltajs commented on arm-templates/subscription.json
> +                "expressionEvaluationOptions": {
Make it oneliner if there is only one child.
Example:
"expressionEvaluationOptions": { scope": "outer" },

2021-09-03 07:33 UTC, paweltajs commented on arm-templates/resources/rg_music_lake.json
> +            "defaultValue": "westeurope"
Use defaultValue only at subscription level. All nested templates should require to pass parameters.

2021-09-03 07:33 UTC, paweltajs commented on arm-templates/resources/rg_music_lake.json
> +            "defaultValue": "nestedParam"
Use defaultValue only at subscription level. All nested templates should require to pass parameters.

2021-09-03 13:09 UTC, curumoLuin commented on arm-templates/subscription.json
> +        "rgNameMusicLake": "[concat('rg-music-lake-', parameters('subPrefix')) ]",
Well aware of that. Uploaded it just to check template linking. Most of errors and trash due to that. Appreciate all feedback non the less.

2021-09-03 21:52 UTC, curumoLuin commented on arm-templates/resources/rg_music_lake.json
> +            "defaultValue": "nestedParam"
Also, just for testing actual outcome.

2021-09-07 07:56 UTC, paweltajs requested changes

2021-09-07 07:56 UTC, paweltajs commented on arm-templates/resources/rg_music_lake.json
> +    "resources": [
Leave resources node empty.

2021-09-07 07:56 UTC, paweltajs commented on arm-templates/subscription.json
> +            "defaultValue": "https://raw.githubusercontent.com/paweltajs/azure-data-lake-infra/"
Include branch name in rootDir parameter.

2021-09-07 16:34 UTC, paweltajs approved these changes
We need to discuss linked templates on next meeting.

2021-09-07 17:31 UTC, merged